#!/bin/sh

makepath=$HOME/conf/bin/makepath
PATH=$($makepath)

eval $(ssh-agent)

export GPG_TTY=$(tty)
gpg-agent --daemon

xset m 1 0 

xmodmap -e "keycode 166 = Prior"
xmodmap -e "keycode 167 = Next"

xscreensaver -no-splash &

exec ratpoison

