
export CONF_DIR=$HOME/conf
export TMPDIR=$HOME/var/tmp
export LOGDIR=$HOME/var/log

export PATH=$($CONF_DIR/bin/makepath path)
export ZSH_DIR=$CONF_DIR/zsh

bindkey -e
export VISUAL=emacs-nox
export EDITOR=emacs-nox

export TMOUT=86400
export HISTFILE=$LOGDIR/zsh_history.log
export HISTSIZE=10000
export SAVEHIST=$HISTSIZE

export TMPPREFIX=$TMPDIR/zsh

autoload -U compinit
compinit

setopt auto_cd
setopt pushd_to_home
setopt append_history
setopt hist_find_no_dups
setopt hist_no_store
setopt hist_reduce_blanks
setopt hist_ignore_space
setopt hist_save_no_dups
setopt hist_verify

umask 022

ulimit -S -c unlimited
ulimit -S -u 1024

if [ $USER = "lloyd" -o $USER = "jlloyd" -o $USER = "randombit" ]; then
   export PS1="(%m %~)%(!.#.$) "
else
   export PS1="(%n@%m %~)%(!.#.$) "
fi

export DATE_DEFAULT_FORMAT="%H:%M:%S %Y-%m-%d"

export LESSHISTFILE=$LOGDIR/less_history.log
export LESTHISTSIZE=200

export CCACHE_DIR=$(makepath ccache)
export LD_LIBRARY_PATH=$(makepath ld_lib $LD_LIBRARY_PATH)
export PYTHONPATH=$(makepath python $PYTHONPATH)
export CLASSPATH=$(makepath classpath $CLASSPATH)
export SCALA_LIB=$(makepath scala)
export MONO_PATH=$(makepath mono)

export TEXINPUTS=$(makepath tex)::

export GRAB_RSS_DIR=$CONF_DIR/grab_rss
export BC_ENV_ARGS=$CONF_DIR/bc.rc
export WORDLIST=$CONF_DIR/ispell.txt
export ASPELL_DIR=$CONF_DIR/aspell
export SCREENRC=$CONF_DIR/screen.rc
export GNUPGHOME=$HOME/var/gnupg

export LESSCOLOR=0
export MANSECT="2:3:1:8:4:5:6:7:9:n:pm:l:p:o"

export BWAY_LOCAL_VARS=$HOME/bway/local.SConscript
export BOTAN_MTN_DB=$HOME/var/mtn/botan.mtn
export MTN_MERGE=emacs

if [ -d $HOME/var/mail ]
then
   alias mutt="mutt -f =Priority"
   export MAILCHECK=10
   export MAILPATH=$(mailpath)
   unset MAIL
fi

LSCOLORSRC=$CONF_DIR/lscolors.rc
if [ -f $LSCOLORSRC ]; then
   eval `dircolors $LSCOLORSRC`
fi
unset LSCOLORSRC

alias reload_profile="unalias -m '*'; source ~/.zshenv"

# Aliases for programs
if [ $OSTYPE = "linux-gnu" ]; then
   alias ls="ls -FX -h --color=tty --time-style=long-iso"

   alias bc="bc -q -l"
   alias du="du -sc -h"
   alias df="df -T -h -x devtmpfs -x tmpfs"
   alias free="free -mt"

   alias less='less --no-lessopen -n --quit-if-one-screen'
   alias nice='ionice -c 3 nice'
#   alias which="alias | which --all --tty-only -i --show-dot --show-tilde"
   alias acpi="acpi -cV"
   alias hibernate='sudo hibernate-ram'

   alias apg="apg -x 12 -m 12"
   alias shred="shred -n 10 -u -z"

   alias syu="sudo pacman -Syu"
   alias aspell="aspell -x --home-dir $ASPELL_DIR --per-conf aspell.rc"
   alias flacinfo="metaflac --export-tags-to=-"
   alias mkisofs="mkisofs -l -J -r -D -d"
   alias cdrecord="cdrecord -v"

   alias mplayer="mplayer -vo gl -stop-xscreensaver -softvol -softvol-max 2000"
   alias headphones_on='amixer set Front unmute'
   alias headphones_off='amixer set Front mute'
else
   alias ls="ls -F"
   alias bc="bc -l"
   alias du="du -sk"
   alias df="df -k"
fi

alias lg="ls -l"
alias l="ls -o"
alias lf="ls -A"
alias la="l -A"
alias ll="ls | less"
alias lr="ls -R"
alias llr="ls -lR"
alias lga="lg -A"
alias llt="ls -l --sort=time -r"

alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"

alias printcert="openssl x509 -text -noout -in"
alias printcert_der="openssl x509 -text -noout -inform DER -in"
alias printpkcs10="openssl req -text -noout -in"
alias printcrl="openssl crl -text -noout -in"
alias printcrl_der="openssl crl -text -noout -inform DER -in"

if [ $DISPLAY ]; then
   function emacs
      {
      command emacs $* &
      disown "command emacs"
      }
fi
